import React, { useState } from 'react';
import { motion } from 'framer-motion';

// ── Schema Definition ──────────────────────────────────────────────────────
interface Column {
  name: string;
  type: string;
  constraint?: string; // PK, FK, UNIQUE, etc.
  ref?: string;        // FK target table
}

interface Table {
  id: string;
  name: string;
  color: string;
  x: number;
  y: number;
  columns: Column[];
  notes?: string;
}

const TABLES: Table[] = [
  {
    id: 'geo_parameter',
    name: 'geo_parameter',
    color: '#f59e0b',
    x: 40,
    y: 30,
    notes: 'Environmental telemetry parameter definitions',
    columns: [
      { name: 'parameter_id', type: 'SERIAL', constraint: 'PK' },
      { name: 'name', type: 'VARCHAR(100)', constraint: 'UNIQUE' },
      { name: 'code', type: 'VARCHAR(20)', constraint: 'UNIQUE' },
      { name: 'unit', type: 'VARCHAR(20)' },
      { name: 'description', type: 'TEXT' },
      { name: 'min_threshold', type: 'DECIMAL' },
      { name: 'max_threshold', type: 'DECIMAL' },
      { name: 'created_at', type: 'TIMESTAMPTZ' },
    ],
  },
  {
    id: 'geo_region',
    name: 'geo_region',
    color: '#3b82f6',
    x: 380,
    y: 30,
    notes: 'Spatial region definitions with GeoJSON boundaries',
    columns: [
      { name: 'region_id', type: 'SERIAL', constraint: 'PK' },
      { name: 'name', type: 'VARCHAR(100)' },
      { name: 'code', type: 'VARCHAR(50)', constraint: 'UNIQUE' },
      { name: 'boundary_json', type: 'JSONB' },
      { name: 'center_lat', type: 'DECIMAL(9,6)' },
      { name: 'center_lon', type: 'DECIMAL(9,6)' },
      { name: 'metadata', type: 'JSONB' },
      { name: 'created_at', type: 'TIMESTAMPTZ' },
    ],
  },
  {
    id: 'telemetry_data',
    name: 'telemetry_data',
    color: '#10b981',
    x: 40,
    y: 310,
    notes: 'Time-partitioned environmental telemetry readings',
    columns: [
      { name: 'telemetry_id', type: 'BIGSERIAL', constraint: 'PK' },
      { name: 'region_id', type: 'INT', constraint: 'FK', ref: 'geo_region' },
      { name: 'parameter_id', type: 'INT', constraint: 'FK', ref: 'geo_parameter' },
      { name: 'value', type: 'DECIMAL' },
      { name: 'lat', type: 'DECIMAL(9,6)' },
      { name: 'lon', type: 'DECIMAL(9,6)' },
      { name: 'recorded_at', type: 'TIMESTAMPTZ', constraint: 'PARTITION KEY' },
      { name: 'metadata', type: 'JSONB' },
    ],
  },
  {
    id: 'adaptive_threshold',
    name: 'adaptive_threshold_config',
    color: '#8b5cf6',
    x: 380,
    y: 310,
    notes: 'Dynamic thresholds computed from regional baselines',
    columns: [
      { name: 'config_id', type: 'SERIAL', constraint: 'PK' },
      { name: 'region_id', type: 'INT', constraint: 'FK', ref: 'geo_region' },
      { name: 'parameter_id', type: 'INT', constraint: 'FK', ref: 'geo_parameter' },
      { name: 'base_mean', type: 'DECIMAL' },
      { name: 'base_stddev', type: 'DECIMAL' },
      { name: 'sensitivity_multiplier', type: 'DECIMAL' },
      { name: 'update_window_days', type: 'INT' },
      { name: 'last_updated', type: 'TIMESTAMPTZ' },
    ],
  },
  {
    id: 'geo_alert',
    name: 'geo_alert',
    color: '#ef4444',
    x: 40,
    y: 590,
    notes: 'Alert events generated by DB triggers',
    columns: [
      { name: 'alert_id', type: 'SERIAL', constraint: 'PK' },
      { name: 'telemetry_id', type: 'BIGINT', constraint: 'FK', ref: 'telemetry_data' },
      { name: 'region_id', type: 'INT', constraint: 'FK', ref: 'geo_region' },
      { name: 'parameter_id', type: 'INT', constraint: 'FK', ref: 'geo_parameter' },
      { name: 'severity', type: 'VARCHAR(20)', constraint: 'CHECK' },
      { name: 'message', type: 'TEXT' },
      { name: 'recorded_value', type: 'DECIMAL' },
      { name: 'threshold_value', type: 'DECIMAL' },
      { name: 'source', type: 'VARCHAR(20)', constraint: 'CHECK' },
      { name: 'status', type: 'VARCHAR(20)', constraint: 'CHECK' },
      { name: 'created_at', type: 'TIMESTAMPTZ' },
    ],
  },
  {
    id: 'region_health',
    name: 'region_health_score',
    color: '#06b6d4',
    x: 380,
    y: 590,
    notes: 'Computed environmental stability index per region',
    columns: [
      { name: 'score_id', type: 'SERIAL', constraint: 'PK' },
      { name: 'region_id', type: 'INT', constraint: 'FK', ref: 'geo_region' },
      { name: 'overall_score', type: 'DECIMAL', constraint: 'CHECK 0-100' },
      { name: 'stability_index', type: 'DECIMAL' },
      { name: 'pollution_index', type: 'DECIMAL' },
      { name: 'risk_level', type: 'VARCHAR(20)' },
      { name: 'calculated_at', type: 'TIMESTAMPTZ' },
    ],
  },
  {
    id: 'users',
    name: 'users',
    color: '#ec4899',
    x: 40,
    y: 940,
    notes: 'RBAC user accounts with role-based access control',
    columns: [
      { name: 'user_id', type: 'SERIAL', constraint: 'PK' },
      { name: 'username', type: 'VARCHAR(50)', constraint: 'UNIQUE' },
      { name: 'email', type: 'VARCHAR(255)', constraint: 'UNIQUE' },
      { name: 'password_hash', type: 'TEXT' },
      { name: 'role', type: 'VARCHAR(20)', constraint: 'CHECK' },
      { name: 'api_key', type: 'VARCHAR(64)', constraint: 'UNIQUE' },
      { name: 'is_active', type: 'BOOLEAN' },
      { name: 'last_login', type: 'TIMESTAMPTZ' },
      { name: 'created_at', type: 'TIMESTAMPTZ' },
    ],
  },
  {
    id: 'audit_log',
    name: 'audit_log',
    color: '#6b7280',
    x: 380,
    y: 940,
    notes: 'Tamper-proof audit trail for all system operations',
    columns: [
      { name: 'log_id', type: 'BIGSERIAL', constraint: 'PK' },
      { name: 'user_id', type: 'INT', constraint: 'FK', ref: 'users' },
      { name: 'username', type: 'VARCHAR(50)' },
      { name: 'action', type: 'VARCHAR(100)' },
      { name: 'resource', type: 'VARCHAR(255)' },
      { name: 'ip_address', type: 'VARCHAR(45)' },
      { name: 'details', type: 'JSONB' },
      { name: 'created_at', type: 'TIMESTAMPTZ' },
    ],
  },
];

// FK Relationships: [from_table, from_col, to_table]
const RELATIONSHIPS: [string, string, string][] = [
  ['telemetry_data', 'region_id', 'geo_region'],
  ['telemetry_data', 'parameter_id', 'geo_parameter'],
  ['adaptive_threshold', 'region_id', 'geo_region'],
  ['adaptive_threshold', 'parameter_id', 'geo_parameter'],
  ['geo_alert', 'region_id', 'geo_region'],
  ['geo_alert', 'parameter_id', 'geo_parameter'],
  ['geo_alert', 'telemetry_id', 'telemetry_data'],
  ['region_health', 'region_id', 'geo_region'],
  ['audit_log', 'user_id', 'users'],
];

const CONSTRAINT_COLORS: Record<string, string> = {
  PK: '#f59e0b',
  FK: '#3b82f6',
  UNIQUE: '#8b5cf6',
  CHECK: '#ef4444',
  'PARTITION KEY': '#10b981',
  'CHECK 0-100': '#ef4444',
};

const TABLE_WIDTH = 300;
const HEADER_H = 34;
const ROW_H = 22;

export const ERDiagram: React.FC = () => {
  const [hoveredTable, setHoveredTable] = useState<string | null>(null);
  const [selectedTable, setSelectedTable] = useState<string | null>(null);

  const tableHeight = (t: Table) => HEADER_H + t.columns.length * ROW_H + 8;

  // Calculate SVG connection lines
  const getConnectionPath = (fromId: string, toId: string): string => {
    const from = TABLES.find(t => t.id === fromId);
    const to = TABLES.find(t => t.id === toId);
    if (!from || !to) return '';

    const fromCx = from.x + TABLE_WIDTH / 2;
    const fromCy = from.y + tableHeight(from) / 2;
    const toCx = to.x + TABLE_WIDTH / 2;
    const toCy = to.y + tableHeight(to) / 2;

    // Determine which side to connect from/to
    let startX: number, startY: number, endX: number, endY: number;

    if (Math.abs(fromCx - toCx) > Math.abs(fromCy - toCy)) {
      // Horizontal connection
      if (fromCx < toCx) {
        startX = from.x + TABLE_WIDTH;
        endX = to.x;
      } else {
        startX = from.x;
        endX = to.x + TABLE_WIDTH;
      }
      startY = fromCy;
      endY = toCy;
    } else {
      // Vertical connection
      if (fromCy < toCy) {
        startY = from.y + tableHeight(from);
        endY = to.y;
      } else {
        startY = from.y;
        endY = to.y + tableHeight(to);
      }
      startX = fromCx;
      endX = toCx;
    }

    const midX = (startX + endX) / 2;
    const midY = (startY + endY) / 2;
    return `M ${startX} ${startY} Q ${midX} ${startY} ${midX} ${midY} Q ${midX} ${endY} ${endX} ${endY}`;
  };

  // Determine which relationships to highlight
  const activeRels = RELATIONSHIPS.filter(
    ([from, , to]) => hoveredTable === from || hoveredTable === to || selectedTable === from || selectedTable === to
  );
  const inactiveRels = RELATIONSHIPS.filter(
    ([from, , to]) => hoveredTable !== from && hoveredTable !== to && selectedTable !== from && selectedTable !== to
  );

  const svgWidth = 730;
  const svgHeight = Math.max(...TABLES.map(t => t.y + tableHeight(t))) + 40;

  return (
    <div className="space-y-4">
      {/* Legend */}
      <div className="flex flex-wrap gap-3 px-1">
        {Object.entries(CONSTRAINT_COLORS).map(([label, color]) => (
          <div key={label} className="flex items-center gap-1.5">
            <div className="w-2.5 h-2.5 rounded-sm" style={{ backgroundColor: color }} />
            <span className="text-[9px] font-bold uppercase tracking-wider" style={{ color: 'var(--text-muted)' }}>{label}</span>
          </div>
        ))}
        <div className="flex items-center gap-1.5">
          <svg width="20" height="8"><line x1="0" y1="4" x2="20" y2="4" stroke="#3b82f6" strokeWidth="1.5" strokeDasharray="3 2" /></svg>
          <span className="text-[9px] font-bold uppercase tracking-wider" style={{ color: 'var(--text-muted)' }}>Foreign Key Relation</span>
        </div>
      </div>

      {/* ER Diagram SVG */}
      <div className="overflow-auto rounded-2xl border" style={{ borderColor: 'var(--border-subtle)', background: 'var(--bg-surface)' }}>
        <svg
          viewBox={`0 0 ${svgWidth} ${svgHeight}`}
          width="100%"
          style={{ minHeight: '500px', maxHeight: '700px' }}
        >
          {/* Grid background */}
          <defs>
            <pattern id="er-grid" width="20" height="20" patternUnits="userSpaceOnUse">
              <path d="M 20 0 L 0 0 0 20" fill="none" stroke="rgba(191,164,64,0.06)" strokeWidth="0.5" />
            </pattern>
            {/* Animated dash pattern for active FK lines */}
            <style>{`
              @keyframes dash-flow {
                to { stroke-dashoffset: -20; }
              }
              .fk-line-active {
                animation: dash-flow 1s linear infinite;
              }
            `}</style>
          </defs>
          <rect width={svgWidth} height={svgHeight} fill="url(#er-grid)" />

          {/* Inactive relationship lines */}
          {inactiveRels.map(([from, col, to], i) => {
            const path = getConnectionPath(from, to);
            return (
              <g key={`rel-inactive-${i}`}>
                <path
                  d={path}
                  fill="none"
                  stroke="rgba(191,164,64,0.15)"
                  strokeWidth="1"
                  strokeDasharray="4 3"
                />
              </g>
            );
          })}

          {/* Active relationship lines */}
          {activeRels.map(([from, col, to], i) => {
            const path = getConnectionPath(from, to);
            const fromTable = TABLES.find(t => t.id === from);
            return (
              <g key={`rel-active-${i}`}>
                <path
                  d={path}
                  fill="none"
                  stroke="#3b82f6"
                  strokeWidth="2"
                  strokeDasharray="6 3"
                  className="fk-line-active"
                  opacity={0.8}
                />
                {/* Label */}
                <text
                  x={(TABLES.find(t => t.id === from)!.x + TABLE_WIDTH / 2 + TABLES.find(t => t.id === to)!.x + TABLE_WIDTH / 2) / 2}
                  y={(TABLES.find(t => t.id === from)!.y + tableHeight(TABLES.find(t => t.id === from)!) / 2 + TABLES.find(t => t.id === to)!.y + tableHeight(TABLES.find(t => t.id === to)!) / 2) / 2 - 6}
                  textAnchor="middle"
                  fill="#3b82f6"
                  fontSize="8"
                  fontWeight="bold"
                  fontFamily="monospace"
                >
                  {col}
                </text>
              </g>
            );
          })}

          {/* Table cards */}
          {TABLES.map((table) => {
            const h = tableHeight(table);
            const isHovered = hoveredTable === table.id;
            const isSelected = selectedTable === table.id;
            const isHighlighted = isHovered || isSelected;

            return (
              <g
                key={table.id}
                onMouseEnter={() => setHoveredTable(table.id)}
                onMouseLeave={() => setHoveredTable(null)}
                onClick={() => setSelectedTable(selectedTable === table.id ? null : table.id)}
                style={{ cursor: 'pointer' }}
              >
                {/* Shadow */}
                <rect
                  x={table.x + 2}
                  y={table.y + 2}
                  width={TABLE_WIDTH}
                  height={h}
                  rx="8"
                  fill="rgba(0,0,0,0.08)"
                />

                {/* Card body */}
                <rect
                  x={table.x}
                  y={table.y}
                  width={TABLE_WIDTH}
                  height={h}
                  rx="8"
                  fill={isHighlighted ? 'rgba(255,255,255,0.98)' : 'rgba(255,255,255,0.92)'}
                  stroke={isHighlighted ? table.color : 'rgba(191,164,64,0.25)'}
                  strokeWidth={isHighlighted ? 2 : 1}
                />

                {/* Header bar */}
                <rect
                  x={table.x}
                  y={table.y}
                  width={TABLE_WIDTH}
                  height={HEADER_H}
                  rx="8"
                  fill={table.color}
                  opacity={isHighlighted ? 1 : 0.85}
                />
                {/* Square off bottom corners of header */}
                <rect
                  x={table.x}
                  y={table.y + HEADER_H - 8}
                  width={TABLE_WIDTH}
                  height={8}
                  fill={table.color}
                  opacity={isHighlighted ? 1 : 0.85}
                />

                {/* Table name */}
                <text
                  x={table.x + 12}
                  y={table.y + 21}
                  fill="white"
                  fontSize="11"
                  fontWeight="800"
                  fontFamily="monospace"
                  letterSpacing="0.5"
                >
                  {table.name}
                </text>

                {/* Column rows */}
                {table.columns.map((col, ci) => {
                  const rowY = table.y + HEADER_H + ci * ROW_H + 4;
                  const constraintColor = col.constraint ? CONSTRAINT_COLORS[col.constraint] || '#6b7280' : undefined;

                  return (
                    <g key={col.name}>
                      {/* Alternating row bg */}
                      {ci % 2 === 0 && (
                        <rect
                          x={table.x + 1}
                          y={rowY - 2}
                          width={TABLE_WIDTH - 2}
                          height={ROW_H}
                          fill="rgba(249,247,237,0.5)"
                          rx="0"
                        />
                      )}

                      {/* Constraint badge */}
                      {col.constraint && (
                        <g>
                          <rect
                            x={table.x + 8}
                            y={rowY + 2}
                            width={constraintColor ? 24 : 20}
                            height={12}
                            rx="3"
                            fill={constraintColor}
                            opacity={0.15}
                          />
                          <text
                            x={table.x + 10}
                            y={rowY + 11}
                            fill={constraintColor}
                            fontSize="7"
                            fontWeight="800"
                            fontFamily="monospace"
                          >
                            {col.constraint === 'PARTITION KEY' ? 'PT' : col.constraint === 'CHECK 0-100' ? 'CK' : col.constraint}
                          </text>
                        </g>
                      )}

                      {/* Column name */}
                      <text
                        x={table.x + (col.constraint ? 38 : 12)}
                        y={rowY + 12}
                        fill="#26221a"
                        fontSize="9.5"
                        fontWeight="600"
                        fontFamily="monospace"
                      >
                        {col.name}
                      </text>

                      {/* Column type */}
                      <text
                        x={table.x + TABLE_WIDTH - 10}
                        y={rowY + 12}
                        fill="#968e78"
                        fontSize="8"
                        fontWeight="500"
                        fontFamily="monospace"
                        textAnchor="end"
                      >
                        {col.type}
                      </text>
                    </g>
                  );
                })}
              </g>
            );
          })}
        </svg>
      </div>

      {/* Selected table details */}
      {selectedTable && (() => {
        const table = TABLES.find(t => t.id === selectedTable);
        if (!table) return null;
        const relatedTables = RELATIONSHIPS
          .filter(([from, , to]) => from === selectedTable || to === selectedTable)
          .map(([from, col, to]) => ({
            direction: from === selectedTable ? 'references' : 'referenced by',
            table: from === selectedTable ? to : from,
            column: col,
          }));

        return (
          <motion.div
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            className="glass-panel-solid rounded-2xl border p-4 space-y-3"
          >
            <div className="flex items-center gap-2">
              <div className="w-3 h-3 rounded-full" style={{ backgroundColor: table.color }} />
              <span className="text-[12px] font-black uppercase tracking-wider font-mono" style={{ color: 'var(--text-primary)' }}>
                {table.name}
              </span>
            </div>
            {table.notes && (
              <p className="text-[10px] font-semibold" style={{ color: 'var(--text-secondary)' }}>{table.notes}</p>
            )}
            <div className="space-y-1">
              <span className="text-[9px] font-black uppercase tracking-wider" style={{ color: 'var(--text-muted)' }}>
                Relationships ({relatedTables.length})
              </span>
              {relatedTables.map((r, i) => (
                <div key={i} className="flex items-center gap-2 text-[10px]">
                  <span className="font-bold text-blue-500">{r.column}</span>
                  <span className="text-[var(--text-muted)]">{r.direction}</span>
                  <span className="font-mono font-bold" style={{ color: 'var(--text-primary)' }}>{r.table}</span>
                </div>
              ))}
            </div>
            <div className="flex flex-wrap gap-2 pt-1 border-t" style={{ borderColor: 'var(--border-subtle)' }}>
              <span className="text-[9px] font-bold px-2 py-0.5 rounded-full bg-amber-100 text-amber-700 border border-amber-200">
                {table.columns.length} columns
              </span>
              {table.columns.some(c => c.constraint === 'PK') && (
                <span className="text-[9px] font-bold px-2 py-0.5 rounded-full bg-amber-50 text-amber-600 border border-amber-200">
                  Primary Key
                </span>
              )}
              {table.columns.filter(c => c.constraint === 'FK').length > 0 && (
                <span className="text-[9px] font-bold px-2 py-0.5 rounded-full bg-blue-50 text-blue-600 border border-blue-200">
                  {table.columns.filter(c => c.constraint === 'FK').length} Foreign Keys
                </span>
              )}
              {table.id === 'telemetry_data' && (
                <span className="text-[9px] font-bold px-2 py-0.5 rounded-full bg-emerald-50 text-emerald-600 border border-emerald-200">
                  RANGE PARTITIONED
                </span>
              )}
            </div>
          </motion.div>
        );
      })()}

      {/* DB Views & Triggers Section */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
        <div className="glass-panel-solid rounded-2xl border p-4 space-y-2">
          <span className="text-[10px] font-black uppercase tracking-wider" style={{ color: 'var(--text-muted)' }}>
            🔁 Active Database Triggers
          </span>
          <div className="space-y-1.5">
            {[
              { name: 'trg_adaptive_alert', event: 'AFTER INSERT', table: 'telemetry_data', fn: 'fn_adaptive_alert_trigger()', status: 'ENABLED' },
              { name: 'trg_fixed_alert', event: 'AFTER INSERT', table: 'telemetry_data', fn: 'fn_fixed_alert_trigger()', status: 'DISABLED' },
            ].map((tr) => (
              <div key={tr.name} className="p-2 rounded-xl border text-[10px] space-y-1" style={{ background: 'var(--surface-alt)', borderColor: 'var(--border-subtle)' }}>
                <div className="flex items-center justify-between">
                  <span className="font-mono font-bold" style={{ color: 'var(--text-primary)' }}>{tr.name}</span>
                  <span className={`text-[8px] font-black px-1.5 py-0.5 rounded-full ${tr.status === 'ENABLED' ? 'bg-emerald-100 text-emerald-700 border border-emerald-200' : 'bg-stone-100 text-stone-500 border border-stone-200'}`}>
                    {tr.status}
                  </span>
                </div>
                <p className="font-mono text-[9px]" style={{ color: 'var(--text-secondary)' }}>
                  {tr.event} ON <span className="font-bold">{tr.table}</span> → {tr.fn}
                </p>
              </div>
            ))}
          </div>
        </div>

        <div className="glass-panel-solid rounded-2xl border p-4 space-y-2">
          <span className="text-[10px] font-black uppercase tracking-wider" style={{ color: 'var(--text-muted)' }}>
            📊 Materialized Views & Functions
          </span>
          <div className="space-y-1.5">
            {[
              { name: 'v_zscore_anomalies', type: 'VIEW', desc: 'Z-score deviation detection (24h window)' },
              { name: 'v_regional_hotspots', type: 'VIEW', desc: 'Alert frequency hotspot analysis' },
              { name: 'v_telemetry_trends', type: 'VIEW', desc: 'LAG() time-series trend analysis' },
              { name: 'fn_calculate_esi()', type: 'FUNCTION', desc: 'Environmental Stability Index computation' },
            ].map((v) => (
              <div key={v.name} className="p-2 rounded-xl border flex items-center justify-between" style={{ background: 'var(--surface-alt)', borderColor: 'var(--border-subtle)' }}>
                <div>
                  <span className="font-mono font-bold text-[10px]" style={{ color: 'var(--text-primary)' }}>{v.name}</span>
                  <p className="text-[9px]" style={{ color: 'var(--text-secondary)' }}>{v.desc}</p>
                </div>
                <span className="text-[8px] font-black px-1.5 py-0.5 rounded-full bg-violet-100 text-violet-700 border border-violet-200">
                  {v.type}
                </span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};
